package tarea3.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class GrupoTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Requisitos({"RF-008"})
  @Test
  public void t1_Creargrupo() {
	    driver.get("http://0.0.0.0:8080/ProyectoSII-war/faces/grupos.xhtml");
	    driver.manage().window().setSize(new Dimension(907, 759));
	    driver.findElement(By.id("grupos:insertar")).click();
	    driver.findElement(By.id("grupo:titulacion")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("grupo:titulacion"));
	      dropdown.findElement(By.xpath("//option[. = 'Ingenieria Informática']")).click();
	    }
	    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
	    driver.findElement(By.id("grupo:curso")).sendKeys("Cuarto");
	    driver.findElement(By.id("grupo:letra")).sendKeys("B");
	    driver.findElement(By.id("grupo:plazas")).sendKeys("30");
	    driver.findElement(By.id("grupo:turno")).sendKeys("Tarde");
	    driver.findElement(By.id("grupo:asignar")).click();
	    driver.findElement(By.id("grupo:visible")).click();
	    driver.findElement(By.id("grupo:accion")).click();
	    assertThat(driver.findElement(By.id("grupos:j_idt20:3:curso")).getText(), is("Tercero"));
	  }
  
//  @Test
//  public void BBDD() {
//    driver.get("http://local:8080/ProyectoSII-war/faces/index.xhtml");
//    driver.manage().window().setSize(new Dimension(908, 760));
//    driver.findElement(By.linkText("BBDD")).click();
//    assertThat(driver.findElement(By.id("grupos:j_idt20:0:titulacion_nombre")).getText(), is("Ingenieria Informática"));
//  }
  @Requisitos({"RF-008"})
  @Test
  public void t3_Actualizargrupo() {
    driver.get("http://0.0.0.0:8080/ProyectoSII-war/faces/grupos.xhtml");
    driver.manage().window().setSize(new Dimension(908, 760));
    driver.findElement(By.id("grupos:j_idt24:0:actualizar")).click();
    driver.findElement(By.id("grupo:titulacion")).click();
    {
      WebElement dropdown = driver.findElement(By.id("grupo:titulacion"));
      dropdown.findElement(By.xpath("//option[. = 'Ingenieria de Computadores']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.id("grupo:curso")).clear();
    driver.findElement(By.id("grupo:curso")).sendKeys("Segundo");
    driver.findElement(By.id("grupo:letra")).clear();
    driver.findElement(By.id("grupo:letra")).sendKeys("B");
    driver.findElement(By.id("grupo:plazas")).clear();
    driver.findElement(By.id("grupo:plazas")).sendKeys("50");
    driver.findElement(By.id("grupo:ingles")).click();
    driver.findElement(By.id("grupo:accion")).click();
    assertThat(driver.findElement(By.id("grupos:j_idt24:0:titulacion_nombre")).getText(), is("Ingenieria de Computadores"));
    assertThat(driver.findElement(By.id("grupos:j_idt24:0:curso")).getText(), is("Segundo"));
    assertThat(driver.findElement(By.id("grupos:j_idt24:0:letra")).getText(), is("B"));
    assertTrue(driver.findElement(By.id("grupos:j_idt24:0:ingles")).isSelected());
    assertThat(driver.findElement(By.id("grupos:j_idt24:0:plazas")).getText(), is("50"));
  }
  
  @Requisitos({"RF-008"})
  @Test
  public void t2_Eliminargrupo() {
    driver.get("http://0.0.0.0:8080/ProyectoSII-war/faces/grupos.xhtml");
    driver.manage().window().setSize(new Dimension(908, 760));
    driver.findElement(By.id("grupos:j_idt24:2:eliminar")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//form[@id=\'grupos\']/table/tbody/tr[3]/td"));
      assert(elements.size() == 0);
    }
  }
  
  
}
